import { useState, useEffect } from 'react';
import api from '../../services/api';

export default function ManagerPlans() {
    const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
    const [plan, setPlan] = useState(null);
    const [assignments, setAssignments] = useState([]);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        fetchPlan();
    }, [date]);

    const fetchPlan = async () => {
        setLoading(true);
        try {
            const response = await api.get('/plans', { params: { date } });
            setPlan(response.data.plan);
            setAssignments(response.data.assignments || []);
        } catch (error) {
            console.error('Failed to fetch plan:', error);
            setPlan(null);
            setAssignments([]);
        } finally {
            setLoading(false);
        }
    };

    const handleExport = async (format) => {
        try {
            if (format === 'csv') {
                const response = await api.get('/plans/export', {
                    params: { date, format: 'csv' },
                    responseType: 'blob'
                });
                const url = window.URL.createObjectURL(new Blob([response.data]));
                const link = document.createElement('a');
                link.href = url;
                link.setAttribute('download', `plan-${date}.csv`);
                document.body.appendChild(link);
                link.click();
                link.remove();
            } else {
                const response = await api.get('/plans/export', { params: { date, format: 'json' } });
                const blob = new Blob([JSON.stringify(response.data, null, 2)], { type: 'application/json' });
                const url = window.URL.createObjectURL(blob);
                const link = document.createElement('a');
                link.href = url;
                link.setAttribute('download', `plan-${date}.json`);
                document.body.appendChild(link);
                link.click();
                link.remove();
            }
        } catch (error) {
            console.error('Export failed:', error);
        }
    };

    return (
        <div>
            <div className="flex justify-between items-center mb-6">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900">📊 View Plans</h1>
                    <p className="text-gray-500">Review and export daily plans</p>
                </div>
            </div>

            <div className="card mb-6">
                <div className="flex items-center gap-4 flex-wrap">
                    <div>
                        <label className="label">Select Date</label>
                        <input
                            type="date"
                            className="input w-auto"
                            value={date}
                            onChange={(e) => setDate(e.target.value)}
                        />
                    </div>
                    {plan && (
                        <>
                            <button onClick={() => handleExport('csv')} className="btn btn-primary">
                                📥 Export CSV
                            </button>
                            <button onClick={() => handleExport('json')} className="btn btn-secondary">
                                📥 Export JSON
                            </button>
                        </>
                    )}
                </div>
            </div>

            {loading ? (
                <div className="text-center py-8">Loading...</div>
            ) : plan ? (
                <div>
                    <div className="card mb-6">
                        <div className="flex items-center gap-6 text-sm">
                            <div>
                                <span className="text-gray-500">Date:</span>{' '}
                                <span className="font-medium">{plan.date}</span>
                            </div>
                            <div>
                                <span className="text-gray-500">Algorithm:</span>{' '}
                                <span className="font-medium">{plan.algorithm}</span>
                            </div>
                            <div>
                                <span className="text-gray-500">Generated by:</span>{' '}
                                <span className="font-medium">{plan.generated_by}</span>
                            </div>
                        </div>
                    </div>

                    <div className="card">
                        <table className="w-full">
                            <thead>
                                <tr className="border-b border-gray-200">
                                    <th className="text-left py-3 px-4 font-semibold text-gray-600">Pharmacist</th>
                                    <th className="text-left py-3 px-4 font-semibold text-gray-600">Pharmacy</th>
                                    <th className="text-left py-3 px-4 font-semibold text-gray-600">Area</th>
                                    <th className="text-left py-3 px-4 font-semibold text-gray-600">Slot</th>
                                    <th className="text-left py-3 px-4 font-semibold text-gray-600">Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {assignments.flatMap((assignment) =>
                                    assignment.pharmacies.map((item, idx) => (
                                        <tr key={`${assignment.pharmacist.id}-${idx}`} className="border-b border-gray-100 hover:bg-gray-50">
                                            <td className="py-3 px-4 font-medium">{assignment.pharmacist.full_name}</td>
                                            <td className="py-3 px-4">{item.pharmacy.name}</td>
                                            <td className="py-3 px-4 text-gray-600">{item.pharmacy.area}</td>
                                            <td className="py-3 px-4 text-gray-600">#{item.slot_index}</td>
                                            <td className="py-3 px-4">
                                                <span className={`px-2 py-1 rounded-full text-xs font-medium ${item.status === 'Done' ? 'bg-green-100 text-green-700' :
                                                        item.status === 'Skipped' ? 'bg-red-100 text-red-700' :
                                                            'bg-blue-100 text-blue-700'
                                                    }`}>
                                                    {item.status}
                                                </span>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>
            ) : (
                <div className="card text-center py-12">
                    <p className="text-gray-500">No plan found for this date.</p>
                </div>
            )}
        </div>
    );
}
